package records;

public class Main {

	public static void main(String[] args) {

		EmployeeClass employee = new EmployeeClass("Jerry", 12345);
		System.out.println(employee.getName()); // getName(); // Jerry
		System.out.println(employee); // generated with IDE
		
		EmployeeRecord employeeRecord = new EmployeeRecord("Kramer", 54321);
		System.out.println(employeeRecord.name()); // name(); // Kramer
		System.out.println(employeeRecord); // generated by record
		System.out.println(employeeRecord.nameInUpperCase()); // KRAMER
		EmployeeRecord.printWhatever(); // Whatever
		
	}

}
